const users = [{
    id: 1,
    username: 'John Doe',
    email: 'john@gmail.com',
    password: 'hashedPassword1',
    image: 'https://img.icons8.com/dusk/64/user.png',
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    id: 2,
    username: 'Jane Smith',
    email: 'jane@gmail.com',
    password: 'hashedPassword2',
    image: 'https://img.icons8.com/dusk/64/user.png',
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    id: 3,
    username: 'Alice Johnson',
    email: 'alice@gmail.com',
    password: 'hashedPassword3',
    image: 'https://img.icons8.com/dusk/64/user.png',
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    id: 4,
    username: 'Bob Brown',
    email: 'bob@gmail.com',
    password: 'hashedPassword4',
    image: 'https://img.icons8.com/dusk/64/user.png',
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    id: 5,
    username: 'Eva Green',
    email: 'eva@gmail.com',
    password: 'hashedPassword5',
    image: 'https://img.icons8.com/dusk/64/user.png',
    createdAt: new Date(),
    updatedAt: new Date(),
},
];

const products = [{
    id: 1,
    name: 'Product 1',
    description: 'Description for product 1',
    price: 100,
    stock: 50,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    id: 2,
    name: 'Product 2',
    description: 'Description for product 2',
    price: 200,
    stock: 30,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    id: 3,
    name: 'Product 3',
    description: 'Description for product 3',
    price: 300,
    stock: 20,
    createdAt: new Date(),
    updatedAt: new Date(),
},

{
    id: 4,
    name: 'Product 4',
    description: 'Description for product 4',
    price: 400,
    stock: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    id: 5,
    name: 'Product 5',
    description: 'Description for product 5',
    price: 500,
    stock: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    id: 6,
    name: 'Product 6',
    description: 'Description for product 6',
    price: 600,
    stock: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    id: 7,
    name: 'Product 7',
    description: 'Description for product 7',
    price: 700,
    stock: 15,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    id: 8,
    name: 'Product 8',
    description: 'Description for product 8',
    price: 800,
    stock: 25,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    id: 9,
    name: 'Product 9',
    description: 'Description for product 9',
    price: 900,
    stock: 35,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    id: 10,
    name: 'Product 10',
    description: 'Description for product 10',
    price: 1000,
    stock: 45,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    id: 11,
    name: 'Product 11',
    description: 'Description for product 11',
    price: 1100,
    stock: 55,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    id: 12,
    name: 'Product 12',
    description: 'Description for product 12',
    price: 1200,
    stock: 65,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    id: 13,
    name: 'Product 13',
    description: 'Description for product 13',
    price: 1300,
    stock: 75,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    id: 14,
    name: 'Product 14',
    description: 'Description for product 14',
    price: 1400,
    stock: 85,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    id: 15,
    name: 'Product 15',
    description: 'Description for product 15',
    price: 1500,
    stock: 95,
    createdAt: new Date(),
    updatedAt: new Date(),
},

{
    id: 16,
    name: 'Product 16',
    description: 'Description for product 16',
    price: 1600,
    stock: 105,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    id: 17,
    name: 'Product 17',
    description: 'Description for product 17',
    price: 1700,
    stock: 115,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    id: 18,
    name: 'Product 18',
    description: 'Description for product 18',
    price: 1800,
    stock: 125,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    id: 19,
    name: 'Product 19',
    description: 'Description for product 19',
    price: 1900,
    stock: 135,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    id: 20,
    name: 'Product 20',
    description: 'Description for product 20',
    price: 2000,
    stock: 145,
    createdAt: new Date(),
    updatedAt: new Date(),
},

{
    id: 21,
    name: 'Product 21',
    description: 'Description for product 21',
    price: 2100,
    stock: 155,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    id: 22,
    name: 'Product 22',
    description: 'Description for product 22',
    price: 2200,
    stock: 165,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    id: 23,
    name: 'Product 23',
    description: 'Description for product 23',
    price: 2300,
    stock: 175,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    id: 24,
    name: 'Product 24',
    description: 'Description for product 24',
    price: 2400,
    stock: 185,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    id: 25,
    name: 'Product 25',
    description: 'Description for product 25',
    price: 2500,
    stock: 195,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    id: 26,
    name: 'Product 26',
    description: 'Description for product 26',
    price: 2600,
    stock: 205,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    id: 27,
    name: 'Product 27',
    description: 'Description for product 27',
    price: 2700,
    stock: 215,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    id: 28,
    name: 'Product 28',
    description: 'Description for product 28',
    price: 2800,
    stock: 225,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    id: 29,
    name: 'Product 29',
    description: 'Description for product 29',
    price: 2900,
    stock: 235,
    createdAt: new Date(),
    updatedAt: new Date(),
},
{
    id: 30,
    name: 'Product 30',
    description: 'Description for product 30',
    price: 3000,
    stock: 245,
    createdAt: new Date(),
    updatedAt: new Date(),
}

];

export { users, products };